services:
  - type: web
    name: medic-ya
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.trsvyznppbdbatkohibp:LAgc191994...@aws-0-ca-central-1.pooler.supabase.com:6543/postgres"
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080" # 7 días
